<body class="">

  <?php $this->load->view('loading_screen'); ?>

  <div class="wrapper ">

    <!-- Top NavBar -->
    <?php $this->load->view('navigation/sidebar'); ?>
    <!-- End of NavBar -->

    <div class="main-panel">

      <!-- Navbar -->
      <?php $this->load->view('navigation/topbar'); ?>
      <!-- End Navbar -->

      <div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-body mr-5 ml-5">
                  <div class="text-center">
                    <h3 class="mb-0 font-weight-bold">  Üyelik ve Kullanım Sözleşmesi</h3>
                  </div>
      
                    <h3 class="mb-0 font-weight-bold"> 1. TARAFLAR ve TANIMLAR </h3>
                <p><span class="font-weight-bold">  1</span> İş bu sözleşme, LT Eğitim Yayıncılık Danışmanlık Limited Şirketi ile Müşteri arasında, Tarafların özgür iradeleriyle müzakere edilerek aşağıda belirtilen hüküm ve koşullarda akdedilmiştir.</p>
                <p><span class="font-weight-bold"> 1.2</span> LT Eğitim Yayıncılık Danışmanlık Limited Şirketi ve Müşteri sözleşme maddelerinde tek başlarına "Taraf", birlikte ise "Taraflar" olarak anılacaktır.</p>
                <p><span class="font-weight-bold"> 1.3</span> İşbu Sözleşmede kullanılan terim ve sözcükler, yürürlükteki mevzuata aykırı düşmemesi şartıyla, aşağıdaki anlamlarda kullanılmış olup Sözleşmede tanımı bulunmayan terim ve sözcükler için ilgili mevzuatta yapılan tanımlamalar geçerli olacaktır.</p>
                <p><span class="font-weight-bold">  1.3.1</span> www.mobsy.com.tr; LT Eğitim Yayıncılık Danışmanlık Limited Şirketi tarafından 634 sayılı Kat Mülkiyeti Kanunu ‘na göre yönetimi yapılan apartman, bina, avm, plaza, site vb. yapılar için geliştirilen aidat takip ve yönetimine ilişkin yazılımı,</p>
                <p><span class="font-weight-bold"> 1.3.2</span> Müşteri; Sözleşmenin imza bölümünde bilgileri bulunan 634 sayılı Kat Mülkiyeti Kanunu'na göre atanmış yönetici veya yönetim kurulu olarak tanımlanan, yetkili kılınmış gerçek veya tüzel kişileri; </p>
                  <p><span class="font-weight-bold">1.3.3</span> Kullanıcı; www.mobsy.com.tr yazılımını kullanan müşteri tarafından, mobsy yazılımına erişim için yetkilendirdiği daire sakini, kat maliki, kiracı, tedarikçi, personel ve benzeri gerçek veya tüzel kişileri, </p>
                <p><span class="font-weight-bold">  1.3.4 </span>Uygulama; İnternet sitesinden veya mobil platformlardan erişilen ve müşteri ile kullanıcının hizmetine sunulan bina yönetim ve aidat takibine ilişkin yazılımı,</p>
                <p><span class="font-weight-bold"> 1.3.5 </span>İnternet Sitesi; www.mobsy.com.tr ve alt alan adlarında faaliyet gösteren internet sitesini, </p>
                <p><span class="font-weight-bold">  1.3.6</span> Sunucu;  Herhangi ağ ortamında diğer cihazların veya istemci bilgisayarların çeşitli isteklerine hizmet vermek amacı ile tasarlanmış özel bilgisayarlardır. </p>
                <p><span class="font-weight-bold">  1.3.7</span> İçerik; Müşteri veya kullanıcıların Mobsy programına girdikleri text, dosya vb. gibi materyalleri,</p>
                  <p><span class="font-weight-bold"> 1.3.8</span> Sistem; Mobsy yazılımının çalışmasını sağlayan yazılım kümesinin bütünüdür.</p>
                  <p><span class="font-weight-bold"> 1.3.9</span> Ziyaretçi; İnternet sitesini müşteri veya kullanıcı olmaksızın ziyaret eden üçüncü kişileri; </p>
                  <p><span class="font-weight-bold">1.3.10</span> Kayıt Formu; Müşteri’nin Mobsy programını kullanmak veya test etmek için internet sitesi üzerinden bina adı, daire sayısı, yönetici bilgileri vb. bilgileri içeren form/formları,</p>
                <p><span class="font-weight-bold"> 1.3.11</span> Hizmet(ler);  634 sayılı Kat Mülkiyeti Kanunu ‘na göre yönetimi yapılan apartman, bina, avm, plaza, site vb. yapılar için LT Eğitim Yayıncılık Danışmanlık Limited Şirketi tarafın geliştirilen Mobsy programının iş bu sözleşme kapsamında belirtilen koşullar kapsamında kullanım hakkını, </p>
                <p><span class="font-weight-bold">  1.3.12</span> Ek Hizmetler; LT Eğitim Yayıncılık Danışmanlık Limited Şirketi tarafından sunulan veya satılan ve bu sözleşme hükümlerine tabi olan diğer hizmetleri,</p>
                <p><span class="font-weight-bold"> 1.3.13</span> Taahhüt İndirimi; Müşterinin belirli bir süre karşılığı vermiş olduğu www.mobsy.com.tr kullanım taahhüdüne karşılık, LT Eğitim Yayıncılık Danışmanlık Limited Şirketi tarafından hizmet bedelinde yapılan indirim, yazılımın ücretsiz kullanımı veya hediye edilen Mobsy başlıklı SMS ‘leri, </p>
                <p><span class="font-weight-bold">  1.3.14</span> Mücbir Sebep; Sözleşmenin imzalandığı tarihte öngörülmesi mümkün olmayan ve Tarafların dahli olmaksızın gelişen ve Tarafların Sözleşme ile yüklendikleri borç ve sorumlulukları kısmen veya tamamen yerine getirmelerini imkânsızlaştıran doğal afetler, harp, seferberlik, yangın, grev ve lokavt veya hükümet veya resmi makamlarca alınmış kararlar ile alt yapı sorunları, telefon şebekelerindeki arızalar, elektrik kesintileri veya benzeri halleri, </p>
                    <p><span class="font-weight-bold">1.3.15</span> Sözleşme; işbu Sözleşme ve eklerini ifade eder.</p>
                    <h3 class="mb-0 font-weight-bold">2. SÖZLEŞME KONUSU ve KAPSAMI </h3>
                    <p><span class="font-weight-bold">  2.1</span> İşbu Sözleşme, Müşteri tarafından, İnternet sitesi üzerinden erişilen bulut tabanlı bina ve site yönetimi uygulamasından (“Mobsy”) faydalanılmasına ve Müşteri ve kullanıcı tarafından Mobsy 'a yüklenen verilere (“İçerik”) ilişkin koşul ve şartlar ile ilgili tarafların hak ve yükümlülüklerinin belirlenmesi amacıyla akdedilmektedir. İnternet sitesi kapsamında Mobsy kullanımına ilişkin olarak LT Eğitim Yayıncılık Danışmanlık Limited Şirketi tarafından Müşteri ve Kullanıcılara sunulan kullanım koşulları, kural ve şartlar da işbu Sözleşme’nin eki ve ayrılmaz bir parçası niteliğinde olup burada yer alan hak ve yükümlülüklerle birlikte tarafların hak ve yükümlülüklerinin tamamını oluşturmaktadır.</p>
                        <h3 class="mb-0 font-weight-bold">  3. SÖZLEŞME SÜRESİ </h3>
                        <p><span class="font-weight-bold">  3.1</span> Sözleşmenin süresi imzalandığı tarihten itibaren 2 (iki) yıl geçerli olup Taraflardan biri Sözleşmenin sona ermesinden 1 (bir) ay öncesine kadar Sözleşmenin yenilenmemesi talebini yazılı olarak diğer tarafa ihtar etmez ise Sözleşme süresinin sona ermesini takiben 2 (iki) yıl süre ile yenilenecektir.</p>
                            <h3 class="mb-0 font-weight-bold">  4. TARAFLARIN HAK ve YÜKÜMLÜLÜKLERİ </h3>
                            <p><span class="font-weight-bold">  4.1</span> Müşteri, işbu Sözleşme’yi akdetmeye yetkili olduğunu, Sözleşme ve eklerinde beyan ettiği bilgilerin doğruluğunu, kendisine sağlanan Hizmetler ‘i işbu Sözleşme kapsamında belirlenmiş kullanım kurallarına uygun olarak kullanacağını, işbu sözleşmede ve Mobsy programında kayıtlı olan bilgilerin doğruluğunu ve bu bilgilerin değişmesi durumunda güncelleyeceğini peşinen kabul ve taahhüt eder. </p>
                              <p><span class="font-weight-bold">4.2</span> Müşteri, Mobsy ‘e girmiş olduğu içeriğin doğruluğundan kendisi sorumludur. Hatalı içerik girişinden kaynaklı yanlış hesaplama veya paylaşımlardan LT Eğitim Yayıncılık Danışmanlık Limited Şirketi sorumlu tutulamaz.</p>
                              <p><span class="font-weight-bold"> 4.3 </span>Müşteri Hizmetler’i, Sözleşme’nin yapıldığı tarihte “olduğu gibi” ve “mevcut haliyle” kabul eder. Mobsy, Müşterinin tüm taleplerinin karşılanacağı garantisini vermez; ancak, hizmet kalitesini arttırmak, kapsamını genişletmek ya da çeşitlendirmek amacıyla hizmet içeriğinde ve özelliklerinde değişiklik yapma, yeni modüller(eklenti) ekleme ve çıkarma hakkını saklı tutar. İşbu değişiklikler çevrimiçi (online) olarak yayınlanacak olup Mobsy ‘un Müşteri’ye ayrıca bir bildirimde bulunma zorunluluğu yoktur. Müşteri’nin, yapılan değişiklikleri gerekçe LT Eğitim Yayıncılık Danışmanlık Limited Şirketi’dan herhangi bir tazminat talep etme hakkı yoktur.  </p>
                              <p><span class="font-weight-bold"> 4.4</span> LT Eğitim Yayıncılık Danışmanlık Limited Şirketi, işbu Sözleşmenin imzalandığı tarihten itibaren, www.mobsy.com.tr yazılımını kendi planları doğrultusunda geliştirilmesi ve sürekli yayınlanması işlerini yapmakla yükümlüdür.</p>
                            <p><span class="font-weight-bold"> 4.5 </span>LT Eğitim Yayıncılık Danışmanlık Limited Şirketi, Hizmetler ‘in kesintisiz ve sürekli olarak sunulması için gerekli tüm önlemleri alacağını ve Hizmetler ‘in herhangi bir nedenle kesintiye uğraması durumunda mümkün olan en kısa sürede duruma müdahale edeceğini taahhüt eder. Ancak Mücbir sebepler nedeniyle Hizmetler’in aksaması veya kesintiye uğramasında LT Eğitim Yayıncılık Danışmanlık Limited Şirketi ‘ın kastı ile oluşmayan diğer her türlü nedenlerden dolayı oluşabilecek kayıp ve zararlardan sorumlu tutulamaz.</p>
                            <p><span class="font-weight-bold">  4.6</span> Müşteri, Mobsy alt yapısı üzerinden göndermiş olduğu SMS ve E-Postaların içeriğinden kendisi sorumludur. Söz konusu iletişim araçlarını ürün ve hizmet satışı, karşı tarafın rızası olmadan gönderilen e-postalar, üçüncü kişilerin yazılım ve bilgisayar sistemlerine zarar verebilecek dosyalar, diğer kullanıcılar bakımından hakaret içeren içerikler yahut hukuka aykırı her türlü içerik de dâhil olmak üzere www.mobsy.com.tr amacı dışında materyaller paylaşmak için kullanmayacaktır. </p>
                            <p><span class="font-weight-bold">  4.7 </span>LT Eğitim Yayıncılık Danışmanlık Limited Şirketi, günlük olarak www.mobsy.com.tr yazılımının veri tabanı yedeğini almakla yükümlüdür. Alınan bu yedeğin genel arıza veya mücbir sebeplerden dolayı doğabilecek olası bir arızada yeniden yüklenmesi için kullanılır. Günlük olarak alınan bu veri tabanı yedeği, program haricinde okunabilir bir yapıda olmadığı için Müşteri ile paylaşılmayacaktır.</p>
                            <p><span class="font-weight-bold"> 4.8 </span>Müşteri, www.mobsy.com.tr uygulamasına giriş yaptığı içeriklerin kopyasını saklamakla yükümlüdür. LT Eğitim Yayıncılık Danışmanlık Limited Şirketi, veri kaybını önlemek için gerekli güvenlik politikalarına ve usullerine uymakla beraber, içerik kaybının yaşanması durumunda yaşanan içerik kaybından sorumlu değildir. </p>
                            <p><span class="font-weight-bold">  4.9 </span>Müşteri, www.mobsy.com.tr kullanımı esnasında kendi içeriklerinin yedeğini “Dışa Aktar” seçeneği ile MS Excel formatında dışa aktararak almak ve tahsilat, gider makbuzları ile çıktı almış olduğu raporları saklamak ve arşivlemek ile yükümlüdür. </p>
                            <p><span class="font-weight-bold">  4.10</span> LT Eğitim Yayıncılık Danışmanlık Limited Şirketi, Müşterilerin telefon veya e-posta ile bildirdikleri makul talepleri değerlendirerek gerekli görülen ve diğer müşterilere de hitap edecek talepleri güncelleme listesine alarak güncellemeler yapabilir. Yapılan bu güncellemeleri Müşteri peşinen kabul ve taahhüt eder.</p>
                              <p><span class="font-weight-bold"> 4.11</span> Müşteri, karşılaştığı hata veya sorunları destek@ltyazilim.com adresine bildirmeleri durumunda LT Eğitim Yayıncılık Danışmanlık Limited Şirketi ’ın en geç 3 (üç) gün içinde cevap vermek ve hatanın önemine göre iş planına almakla yükümlüdür. </p>
                              <p><span class="font-weight-bold">4.12</span> Müşteri, kullanım süresi içerisinde ödeme yapacağı günleri takip etmekle ve son ödeme gününden önce ödemek ile yükümlüdür. Ödeme yapılmaması durumunda www.mobsy.com.tr sistem tarafından otomatik olarak durdurulacak ve Müşteri ‘nin programa girişi engellenecektir. Bu durumdan doğabilecek olumsuzluklardan LT Eğitim Yayıncılık Danışmanlık Limited Şirketi sorumlu tutulamaz. 4.13 Müşteri tarafından kullanım ücreti ödenmeyen hesaplar sistem tarafından 15 (on beş) gün sonra pasif edilir ve 15 (on beş) gün sonra da tamamen silinir.</p>
                              <p><span class="font-weight-bold"> 4.14</span> Müşteri, kullanım ücretini ödemeyerek pasife alınan veya silinen hesapları için sonradan LT Eğitim Yayıncılık Danışmanlık Limited Şirketi ‘den bilgi veya belge talebinde bulunamaz.</p>
                              <p><span class="font-weight-bold"> 4.15</span> Müşteri, www.mobsy.com.tr yazılımına kendi belirlemiş olduğu E-Posta adresi ve şifre ile giriş yapmaktadır. Şifre güvenliğinin kendisi sorumlu olup, kolay tahmin edilebilir bir şifre tanımlamamalı, e-posta adresinin çalınması durumunda derhal LT Eğitim Yayıncılık Danışmanlık Limited Şirketi ‘a bilgi vermesi, ortak kullanılan bilgisayarlardan www.mobsy.com.tr ‘a giriş yapması durumunda işlemlerinin bitiminden sonra mutlaka çıkış yapmalıdır. Belirtilen durumlardan kaynaklı olası bir veri kaybı, içerik girişi vb. durumlarından LT Eğitim Yayıncılık Danışmanlık Limited Şirketi sorumlu değildir. </p>
                            <p><span class="font-weight-bold">  4.16</span> LT Eğitim Yayıncılık Danışmanlık Limited Şirketi, herhangi bir ön bildirimde bulunmaksızın işbu Sözleşme ve eklerini revize etme hakkına sahip olup www.mobsy.com.tr yazılımını kullanılması halinde ilgili değişiklik Müşteri’nin bir sonraki yenileme döneminde yürürlüğe girecektir. Müşteri ‘nin söz konusu değişiklikleri kabul etmemesi halinde işbu Sözleşme ’yi aşağıda belirtilen şekilde feshetme hakkı saklıdır.</p>
                              <p><span class="font-weight-bold"> 4.17</span> Müşteri, www.mobsy.com.tr hesabını ve işbu Sözleşme ile Site kullanımından doğan hak ve yükümlülüklerini herhangi bir şekilde üçüncü bir kişiye devir veya temlik edemez.</p>
                              <p><span class="font-weight-bold"> 4.18</span> Müşteri, işbu Sözleşme kapsamında yer alan diğer koşullar ve şartlar ile bu beyanda taahhütlerine aykırı davranması durumunda LT Eğitim Yayıncılık Danışmanlık Limited Şirketi sözleşme ’yi feshederek Müşteri statüsünü sona erdirme hakkına sahip olacaktır.  </p>
                                <h3 class="mb-0 font-weight-bold">5. ÜCRET ve ÖDEME KOŞULLARI </h3>
                              <p><span class="font-weight-bold">5.1</span> www.mobsy.com.tr, ön ödemeli olarak çalışmaktadır. Müşteri, Hizmetler karşılığında aksi ayrıca yazılı olarak belirtilmedikçe, sözleşme ekinde belirtilen teklif veya program içerisinde belirtilen ücreti, belirtilen son ödeme gününde peşinen ödemeyi kabul ve taahhüt eder.</p>
 <p><span class="font-weight-bold">5.2</span> Kullanım ücretleri bağımsız bölümün daire sayısına göre hesaplanır ve seçilen ödeme periyodlarında fatura edilir.</p>
                              <p><span class="font-weight-bold"> 5.3</span> Ödeme periyodları aylık, yıllık, 2 yıllık veya özel teklif olarak belirtilen sürelerde yapılmaktadır. </p>
                              <p><span class="font-weight-bold">5.4</span> Daire sayısı ve ödeme periyoduna göre belirlenen kullanım ücreti sözleşme sonrasında fatura edilir LT Eğitim Yayıncılık Danışmanlık Limited Şirketi 4691 sayılı kanun uyarınca KDV ‘den muaftır. Kullanım ücreti + 0 KDV olarak fatura edilir.</p>
                              <p><span class="font-weight-bold"> 5.5</span> Müşteri, www.mobsy.com.tr kullanmak için beyan edilen ücretleri, ödeme koşulları ve araçları ile tam ve eksiksiz olarak ödemesi karşılığında faydalanabilecektir.</p>
                              <p><span class="font-weight-bold"> 5.6</span> Müşteri, www.mobsy.com.tr ‘u denemek için oluşturduğu hesabı 14 (on dört) gün süre ile ücretsiz kullanabilir. Deneme periyodunun sonunda Müşteri kullanmaya devam etmek isterse kullanım ücretini ödemek koşuluyla www.mobsy.com.tr ‘u kullanmaya devam eder. </p>
                              <p><span class="font-weight-bold">5.7</span> Müşteri, deneme periyodunda veya sonrasında kart bilgilerini tanımlamış ve aksi belirtilmemiş veya üyelik iptal edilmemiş ise üyelik periyodların da üyeliği otomatik olarak yenilenir.</p>
                              <p><span class="font-weight-bold"> 5.8</span> Kullanım ücretleri www.mobsy.com.tr yazılımı içerisinden kredi kartı ile ödeyebilir veya LT Eğitim Yayıncılık Danışmanlık Limited Şirketi TR85 0006 4000 0011 2530 2040 00 IBAN numarasına havale edilir.</p>
                                    <h3 class="mb-0 font-weight-bold">6. FİKRİ MÜLKİYET HAKLARI </h3>
                              <p><span class="font-weight-bold">6.1</span> İnternet Sitesi ve www.mobsy.com.tr üzerindeki her türlü hak, mülkiyet ve menfaat LT Eğitim Yayıncılık Danışmanlık Limited Şirketi’a aittir. İşbu Sözleşme kapsamında Müşteri’ye İnternet Sitesi ve www.mobsy.com.tr kullanmak üzere kişiye özel, dünya çapında, telifsiz, devredilemez ve münhasır olmayan lisans verilmektedir. Sözleşme ve İnternet Sitesi’ne ilişkin diğer koşullardaki hiçbir hüküm İnternet Sitesi ve www.mobsy.com.tr ilişkin hakların ve menfaatlerin Müşteri’ye devredildiği şeklinde yorumlanamaz. Müşteri, işbu Sözleşme kapsamında LT Eğitim Yayıncılık Danışmanlık Limited Şirketi’a Müşteri’nin www.mobsy.com.tr erişimi, www.mobsy.com.tr kullanması ve hizmetlerin sağlanmasına yönelik diğer amaçlarla, bilgilerinin ve İçerik’in kullanılması, kopyalanması, iletilmesi, saklanması ve yedeğinin alınması için kullanım hakkı tanımaktadır. LT Eğitim Yayıncılık Danışmanlık Limited Şirketi, hizmetlerin sağlanması amacıyla İçerik’e ilişkin olarak üçüncü kişi geliştiricilere alt lisans verme hakkını haizdir.</p>
                              <p><span class="font-weight-bold"> 6.2</span> Müşteri, hiçbir şekilde ve nedenle İnternet Sitesi’ni veya www.mobsy.com.tr kopyalama, değiştirme, çoğaltma, ters mühendisliğe tabi tutma, geri derleme ve sair şekillerde İnternet Sitesi üzerindeki yazılımın kaynak koduna ulaşma, İnternet Sitesi’nden işleme eser oluşturma hakkına sahip değildir. İnternet Sitesi’ne ilişkin tarayıcı ve içeriklerin herhangi bir şekilde değiştirilmesi, LT Eğitim Yayıncılık Danışmanlık Limited Şirketi’ın açık izni olmaksızın İnternet Sitesi’ne veya İnternet Sitesi’nden link verilmesi kesinlikle yasaktır.</p>
                              <p><span class="font-weight-bold"> 6.3</span> Müşteri, herhangi bir şekilde LT Eğitim Yayıncılık Danışmanlık Limited Şirketi’ın (veya bağlı şirketlerinin) ticari unvanını, markasını, hizmet markasını, logosunu, alan adını vs. kullanmayacaktır.</p>
                                <h3 class="mb-0 font-weight-bold">  7. SÖZLEŞMENİN YÜRÜRLÜLÜĞÜ ve FESHİ </h3>
                                  <p><span class="font-weight-bold">7.1 </span>İşbu Sözleşme Müşteri tarafından kabulü birlikte yürürlüğe girecek ve taraflardan herhangi biri tarafından aşağıda belirtilen şekilde feshedilmediği sürece yürürlükte kalacaktır.</p>
                              <p><span class="font-weight-bold"> 7.2</span> Taraflardan herhangi biri, diğer tarafça bildirilen elektronik posta adresine 1 (bir) hafta önceden yapacağı yazılı bir bildirimle işbu Sözleşme ’yi dilediği zaman herhangi bir gerekçe göstermeksizin ve tazminat ödemeksizin feshedebilecektir. </p>
                              <p><span class="font-weight-bold">7.3</span> Sözleşme süresi dolmadan Müşteri ‘nin fesih talebi olması durumunda sözleşme öncesi hediye edilen hizmet veya ürünlerin ücreti Müşteriden talep edilebilecektir. </p>
                            <p><span class="font-weight-bold">  7.4</span> Taraflardan birinin işbu Sözleşme ’den kaynaklanan yükümlülüklerini tam ve gereği gibi yerine getirmemesi ve diğer tarafça yapılacak yazılı bildirime karşın söz konusu aykırılığın verilen süre içerisinde giderilmemesi halinde bu Sözleşme bildirimi yapan tarafça feshedilebilecektir. Bahsi geçen aykırılığın Müşteri tarafından gerçekleştirilmesi halinde LT Eğitim Yayıncılık Danışmanlık Limited Şirketi aykırılık giderilene kadar Müşteri statüsünü askıya alma hakkına sahip olacaktır. Müşteri ’nin yürürlükteki mevzuatı ihlal etmesi halinde LT Eğitim Yayıncılık Danışmanlık Limited Şirketi Sözleşme ’yi derhal geçerli olacak şekilde haklı nedenle feshedebilecektir.</p>
                              <p><span class="font-weight-bold"> 7.5</span> Sözleşme’nin feshi Tarafların fesih tarihine kadar doğmuş olan hak ve yükümlülüklerini ortadan kaldırmayacaktır. Sözleşme’nin feshi ile birlikte Müşteri, o güne kadar doğmuş olan tüm ücret ve masraflardan sorumlu olup fesih tarihi itibariyle İnternet Sitesi ve www.mobsy.com.tr’u kullanamayacaktır. Ön ödemeli üyeliklerin feshi halinde Müşteri’ye para iadesi yapılmaz. </p>
                              <p><span class="font-weight-bold">7.6</span> Müşteri ’nin hesabının 3 (üç) ay boyunca pasif olması halinde LT Eğitim Yayıncılık Danışmanlık Limited Şirketi işbu Sözleşme ’yi feshedebilecektir. </p>
                              <p><span class="font-weight-bold">7.7</span> Sözleşme’nin feshedildiği hallerde LT Eğitim Yayıncılık Danışmanlık Limited Şirketi Müşteri’ye ait İçerik ’i saklamak zorunda değildir.   </p>
                                <h3 class="mb-0 font-weight-bold">8. SIR SAKLAMA ve GİZLİLİK HÜKÜMLERİ </h3>
                              <p><span class="font-weight-bold">8.1</span> Taraflar, iş bu sözleşme kapsamında kendisine verilen/iletilen bilgilerle, başta ürün, hizmet fiyatları ile müşteri bilgileri olmak üzere, bu sayılanlarla sınırlı olmaksızın gerek yazılı gerekse elektronik ortamda, öğrendiği tüm bilgileri ve iş bu sözleşmedeki finansal hükümleri gizli bilgi ve ticari sır olarak kabul edeceğini, bu bilgileri hiçbir gerekçe ile ifşa etmeyeceğini ve üçüncü şahıslarla paylaşmayacağını, iş bu maddeye aykırı hareket etmesi durumunda karşı tarafın uğrayacağı zararların giderileceğini kabul eder. </p>
                              <p><span class="font-weight-bold"> 8.2</span> LT Eğitim Yayıncılık Danışmanlık Limited Şirketi, Müşteri’nin hizmetleri kapsamda barındırdığı bilgi, dosya vb. dokümanları yürürlükte olan mevzuat veya verilmiş olan bir mahkeme kararı ya da idari emir gereğince açıklaması zorunlu olduğu durumlarda üçüncü kişi ya da kurumlarla paylaşabilir. Bu durumdan dolayı Müşteri, LT Eğitim Yayıncılık Danışmanlık Limited Şirketi’den herhangi bir hak ya da tazminat talebinde bulunamaz.  </p>
                                <h3 class="mb-0 font-weight-bold">9. DİĞER HÜKÜMLER </h3>
                              <p><span class="font-weight-bold">9.1</span> Sözleşme, 634 s. Kat Mülkiyeti Kanunu uyarınca atanmış yönetici veya yönetim kurulu olarak tanımlanan, yetkili kılınmış gerçek veya tüzel kişilerin her ne sebeple olursa olsun değişmesi halinde dahi geçerliliğini ve bağlayıcılığını sürdürür.</p>
                              <p><span class="font-weight-bold"> 9.2</span> Sözleşme ve ekleri, Taraflar arasındaki Sözleşme’nin tamamını teşkil eder. Sözleşme dışında, Sözleşme öncesi ve sonrasında Taraflar arasında yapılan görüşmeler ve müzakereler kapsamındaki beyanlar Sözleşme’nin bir parçası değildir ve Sözleşme hükümleri ancak yazılı olarak değiştirilebilir. Sözleşme maddelerinden biri veya birkaçının herhangi bir nedenle geçersiz olması halinde, Sözleşme’nin diğer maddeleri geçerliliğini koruyacaktır.</p>
                              <p><span class="font-weight-bold"> 9.3</span> LT Eğitim Yayıncılık Danışmanlık Limited Şirketi sorumluluğunu sınırlayan hükümlerden birinin yetkili mahkeme tarafından mevzuata aykırı bulunması halinde söz konusu hüküm mevzuata uygun olan ve LT Eğitim Yayıncılık Danışmanlık Limited Şirketi 'ın sorumluluğunu en fazla sınırlayan hali ile geçerli sayılacak ve LT Eğitim Yayıncılık Danışmanlık Limited Şirketi 'ın Sözleşme’den doğan sorumluluğu buna uygun olarak belirlenecektir. </p>
 <p><span class="font-weight-bold">9.4</span> Sözleşme’de belirtilen Tarafların adresleri Tarafların tebligat adresleri olup Sözleşme kapsamında yapılacak tebligatlar bu adreslere yapılacaktır. Müşteri, tebligat adresinin değişmesi halinde değişen adresi LT Eğitim Yayıncılık Danışmanlık Limited Şirketi’a derhal bildirmekle yükümlüdür. Aksi taktirde, bu Sözleşme’de bulunan adresi geçerli tebligat adresi olarak kabul edilecektir.</p>
 <p><span class="font-weight-bold">9.5</span> LT Eğitim Yayıncılık Danışmanlık Limited Şirketi Müşteriler’e sunduğu Hizmetler kapsamında üçüncü gerçek veya tüzel kişilerle çalışabilir. Müşteri ile LT Eğitim Yayıncılık Danışmanlık Limited Şirketi 'ın çalıştığı üçüncü kişiler arasında yapılacak sözleşmelerde LT Eğitim Yayıncılık Danışmanlık Limited Şirketi taraf olmayacağı gibi LT Eğitim Yayıncılık Danışmanlık Limited Şirketi üçüncü kişiler tarafından Müşteri’ye verilecek hizmetlere ilişkin herhangi bir sorumluluğu yoktur.</p>
 <p><span class="font-weight-bold">9.6</span> Müşteri, işbu Sözleşme’nin ifasından doğacak her türlü uyuşmazlıkta, LT Eğitim Yayıncılık Danışmanlık Limited Şirketi 'ın' sunduğu Hizmetler’e ilişkin olarak oluşturduğu kayıtların geçerli ve bağlayıcı olduğunu ve kesin delil teşkil edeceğini ve işbu maddenin 6100 sayılı HMK’nın 193. maddesi anlamında bir yazılı delil sözleşmesi beyanı anlamında olduğunu kabul, beyan ve taahhüt eder.</p>
 <p><span class="font-weight-bold">9.7</span> Sözleşme’den doğacak uyuşmazlıkları çözmeye Kayseri Mahkemeleri ve İcra Daireleri yetkilidir ve Sözleşme Türkiye Cumhuriyeti hukukuna tabidir. </p>
                              <p><span class="font-weight-bold">9.8</span> İşbu Sözleşme Müşteri 'nin www.mobsy.com.tr sitesine üye olması ile yürürlüğe girmiş ve bu sözleşmeyi peşinen kabul etmiş sayılmaktadır.</p>
              </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
